static const char *RcsId = "$Header$";
//+=============================================================================
//
// file :         AdlinkDIOStateMachine.cpp
//
// description :  C++ source for the AdlinkDIO and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: rsune $
//
// $Revision: 2935 $
//
// $Log$
// Revision 1.1  2007/08/09 11:03:35  rsune
// Initial import: Device for digital input ports for Adlink acquisition boards
//
//
// copyleft :   CELLS/ALBA
//		Edifici Ciences Nord
//		Campus Universitari de Bellaterra
//		Universitat Autonoma de Barcelona
//		08193 Bellaterra, Barcelona, SPAIN
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//=============================================================================

#include <tango.h>
#include <AdlinkDIO.h>
#include <AdlinkDIOClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace AdlinkDIO_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		AdlinkDIO::is_BoardPorts_allowed
// 
// description : 	Read/Write allowed for BoardPorts attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkDIO::is_BoardPorts_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkDIO::is_PortTemplateBOOLEAN_allowed
// 
// description : 	Read/Write allowed for PortTemplateBOOLEAN attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkDIO::is_PortTemplateBOOLEAN_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkDIO::is_PortTemplateUSHORT_allowed
// 
// description : 	Read/Write allowed for PortTemplateUSHORT attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkDIO::is_PortTemplateUSHORT_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkDIO::is_PortTemplateLONG_allowed
// 
// description : 	Read/Write allowed for PortTemplateLONG attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkDIO::is_PortTemplateLONG_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================


}	// namespace AdlinkDIO_ns
