static const char *RcsId = "$Header$";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: rsune $
//
// $Revision: 2934 $
//
// $Log$
// Revision 1.1  2007/08/09 11:03:35  rsune
// Initial import: Device for digital input ports for Adlink acquisition boards
//
//
// copyleft :   CELLS/ALBA
//		Edifici Ciences Nord
//		Campus Universitari de Bellaterra
//		Universitat Autonoma de Barcelona
//		08193 Bellaterra, Barcelona, SPAIN
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//=============================================================================


#include <tango.h>
#include <AdlinkDIOClass.h>
#include <AdlinkIODSClass.h>

/**
 *	Create AdlinkDIOClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{

	add_class(AdlinkDIO_ns::AdlinkDIOClass::init("AdlinkDIO"));
	add_class(AdlinkIODS_ns::AdlinkIODSClass::init("AdlinkIODS"));

}
