

all: doxygen-make devel-make

clean: doxygen-clean devel-clean

doxygen-make:
	cd doxygen && make
doxygen-clean:
	cd doxygen && make clean

devel-make:
	cd devel && make
devel-clean:
	cd devel && make clean

