static const char *RcsId = "$Header:  $";
//+=============================================================================
//
// file :         AdlinkIOCounterStateMachine.cpp
//
// description :  C++ source for the AdlinkIOCounter and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <AdlinkIOCounter.h>
#include <AdlinkIOCounterClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace AdlinkIOCounter_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_SoftwareControlGate_allowed
// 
// description : 	Read/Write allowed for SoftwareControlGate attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_SoftwareControlGate_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_SoftwareControlUpDown_allowed
// 
// description : 	Read/Write allowed for SoftwareControlUpDown attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_SoftwareControlUpDown_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_Mode_allowed
// 
// description : 	Read/Write allowed for Mode attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_Mode_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_SourceTimeBase_allowed
// 
// description : 	Read/Write allowed for SourceTimeBase attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_SourceTimeBase_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_SourceGate_allowed
// 
// description : 	Read/Write allowed for SourceGate attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_SourceGate_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_SourceUpDown_allowed
// 
// description : 	Read/Write allowed for SourceUpDown attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_SourceUpDown_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PolarityLowGate_allowed
// 
// description : 	Read/Write allowed for PolarityLowGate attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PolarityLowGate_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PolarityLowUpDown_allowed
// 
// description : 	Read/Write allowed for PolarityLowUpDown attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PolarityLowUpDown_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PolarityLowClockEn_allowed
// 
// description : 	Read/Write allowed for PolarityLowClockEn attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PolarityLowClockEn_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PolarityLowOutput_allowed
// 
// description : 	Read/Write allowed for PolarityLowOutput attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PolarityLowOutput_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_InitialCount_allowed
// 
// description : 	Read/Write allowed for InitialCount attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_InitialCount_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PulseDelay_allowed
// 
// description : 	Read/Write allowed for PulseDelay attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PulseDelay_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_PulseWidth_allowed
// 
// description : 	Read/Write allowed for PulseWidth attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_PulseWidth_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code
		if ( (get_state() == Tango::RUNNING) && (type == Tango::READ_REQ))
			return true;
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_Value_allowed
// 
// description : 	Read/Write allowed for Value attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_Value_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_StatusRegister_allowed
// 
// description : 	Read/Write allowed for StatusRegister attribute.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_StatusRegister_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_Reset_allowed
// 
// description : 	Execution allowed for Reset command.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_Reset_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		AdlinkIOCounter::is_Start_allowed
// 
// description : 	Execution allowed for Start command.
//
//-----------------------------------------------------------------------------
bool AdlinkIOCounter::is_Start_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::RUNNING	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

}	// namespace AdlinkIOCounter_ns
